name       : retroshare
version    : 0.6.2
release    : 3
source     :
    - https://github.com/RetroShare/RetroShare/archive/v0.6.2.tar.gz : 76a3ae2f2089b14562d5be34602f5ae3c73a8549aecee246ea5e67d03018de2b
license    : GPL-2.0
component  : network.clients
summary    : RetroShare is a decentralized, private and secure commmunication and sharing platform. RetroShare provides filesharing, chat, messages, forums and channels.
description: |
    RetroShare is a decentralized, private and secure commmunication and sharing platform. RetroShare provides filesharing, chat, messages, forums and channels.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(gnome-keyring-1)
    - pkgconfig(libavcodec)
    - pkgconfig(libcurl)
    - pkgconfig(libmicrohttpd)
    - pkgconfig(libupnp)
    - pkgconfig(libxslt)
    - pkgconfig(opencv)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(speexdsp)
    - pkgconfig(sqlcipher)
    - pkgconfig(x11)
    - pkgconfig(xscrnsaver)
setup      : |
    %qmake CONFIG+=release
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
