name       : retroshare
version    : 0.6.3
release    : 8
source     :
    - https://github.com/RetroShare/RetroShare/archive/v0.6.3.tar.gz : ddb64aa5148fdc950d4426f52f1cbb11578619b1242614e3c4ca4792ee5ce30b
license    : GPL-2.0
component  : network.clients
summary    : RetroShare is a decentralized, private and secure commmunication and sharing platform
description: |
    RetroShare is a decentralized, private and secure commmunication and sharing platform. RetroShare provides filesharing, chat, messages, forums and channels.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(gnome-keyring-1)
    - pkgconfig(libavcodec)
    - pkgconfig(libcurl)
    - pkgconfig(libmicrohttpd)
    - pkgconfig(libupnp)
    - pkgconfig(libxslt)
    - pkgconfig(opencv)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(speexdsp)
    - pkgconfig(sqlcipher)
    - pkgconfig(x11)
    - pkgconfig(xscrnsaver)
    - bzip2-devel
setup      : |
    %qmake LIB_DIR=%libdir% CONFIG-=debug CONFIG+=release
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
