name       : retroshare
version    : 0.6.1
release    : 2
source     :
    - https://github.com/RetroShare/RetroShare/archive/0.6.1.tar.gz : 4ffbb6c61538f80d0f667c2a155c5eac38b0722a3e8d4f1dc1487d10087cfe42
license    : GPL-2.0
component  : network.clients
summary    : RetroShare is a decentralized, private and secure commmunication and sharing platform. RetroShare provides filesharing, chat, messages, forums and channels.
description: |
    RetroShare is a decentralized, private and secure commmunication and sharing platform. RetroShare provides filesharing, chat, messages, forums and channels.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(gnome-keyring-1)
    - pkgconfig(libavcodec)
    - pkgconfig(libmicrohttpd)
    - pkgconfig(libupnp)
    - pkgconfig(opencv)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(speexdsp)
    - pkgconfig(sqlcipher)
    - pkgconfig(x11)
    - pkgconfig(xscrnsaver)
setup      : |
    %qmake CONFIG+=release
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
