name       : retroshare
version    : 0.6.4
release    : 9
source     :
    - https://github.com/RetroShare/RetroShare/archive/v0.6.4.tar.gz : 84355c0f3be5ec1dfa7253e327ea1254f76f47739c233cfb8d0983ebd1a61f4a
license    : GPL-2.0-or-later
component  : network.clients
summary    : RetroShare is a decentralized, private and secure commmunication and sharing platform
description: |
    RetroShare is a decentralized, private and secure commmunication and sharing platform. RetroShare provides filesharing, chat, messages, forums and channels.
builddeps  :
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(gnome-keyring-1)
    - pkgconfig(libavcodec)
    - pkgconfig(libcurl)
    - pkgconfig(libmicrohttpd)
    - pkgconfig(libupnp)
    - pkgconfig(libxslt)
    - pkgconfig(opencv)
    - pkgconfig(speexdsp)
    - pkgconfig(sqlcipher)
    - pkgconfig(x11)
    - pkgconfig(xscrnsaver)
    - bzip2-devel
setup      : |
    %patch -p1 < $pkgfiles/fix-for-Qt-5.11.patch

    %qmake LIB_DIR=%libdir% CONFIG-=debug CONFIG+=release
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
