name       : retroshare
version    : 0.6.6
release    : 16
source     :
    - git|https://github.com/RetroShare/RetroShare.git : v0.6.6
license    : GPL-2.0-or-later
component  : network.clients
summary    : RetroShare is a decentralized, private and secure commmunication and sharing platform
description: |
    RetroShare is a decentralized, private and secure commmunication and sharing platform. RetroShare provides filesharing, chat, messages, forums and channels.
builddeps  :
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(RapidJSON)
    - pkgconfig(gnome-keyring-1)
    - pkgconfig(libavcodec)
    - pkgconfig(libcurl)
    - pkgconfig(libupnp)
    - pkgconfig(libxslt)
    - pkgconfig(opencv4)
    - pkgconfig(speexdsp)
    - pkgconfig(sqlcipher)
    - pkgconfig(x11)
    - pkgconfig(xscrnsaver)
    - bzip2-devel
setup      : |
    %patch -p1 < $pkgfiles/fix_create_directories.patch
    %qmake LIB_DIR=%libdir% CONFIG-=debug CONFIG+=release
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
